site_name: Notas musicais
repo_url: https://github.com/PatrickWyllian/notas-musicais
repo_name: PatrickWyllian/notas-musicais
edit_uri: tree/master/docs

theme:
  name: material
  language: pt-BR
  logo: assets/pngwing.com.png

markdown_extensions:
  - attr_list
extra_css:
  - stylesheets/extra.css  
  



  